global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: mysql-master
    static_configs:
      - targets: ["mysql-exporter-master:9104"]

  - job_name: mysql-slave
    static_configs:
      - targets: ["mysql-exporter-slave:9104"]

  - job_name: apache
    static_configs:
      - targets: ["apache-exporter:9117"]

  - job_name: node-backup
    static_configs:
      - targets: ["svveltrobackup:9100"]