global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 25s

scrape_configs:
  # Auto-monitoreo de Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'monitoring'

  # MySQL Master
  - job_name: 'mysql-master'
    static_configs:
      - targets: ['192.168.20.52:9104']
        labels:
          instance: 'svveltrobdm'
          alias: 'mysql-master'
          role: 'database'
          replication_role: 'master'

  # MySQL Slave
  - job_name: 'mysql-slave'
    static_configs:
      - targets: ['192.168.20.53:9104']
        labels:
          instance: 'svveltrobds'
          alias: 'mysql-slave'
          role: 'database'
          replication_role: 'slave'

  # Backup Server Node Exporter
  - job_name: 'node-backup'
    static_configs:
      - targets: ['192.168.20.30:9100']
        labels:
          instance: 'svveltrobackup'
          service: 'backup'
          role: 'backup-server'
    scrape_interval: 30s